[package]
name = "gix-reftable-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
gix-hash = { path = "../../gix-hash", features = ["sha1", "sha256"] }
libfuzzer-sys = "0.4"
tempfile = "3.27.0"

[dependencies.gix-reftable]
path = ".."
features = ["sha1", "sha256"]

# Prevent this package from interfering with the parent workspace.
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "table"
path = "fuzz_targets/table.rs"
test = false
doc = false

[[bin]]
name = "stack_list"
path = "fuzz_targets/stack_list.rs"
test = false
doc = false
